import type { SearchDestination } from "@/lib/global-search";

/* -------------------------------------------------------------------------
   EVERY DESTINATION, AND EVERY WORD SOMEBODY MIGHT USE FOR IT

   One list, not keywords scattered through components. Each entry carries the
   official name in both languages, the words the business actually uses,
   Arabizi spellings, old page names and the common misspellings — because the
   search is only as good as the vocabulary it was given.
------------------------------------------------------------------------- */

/** Words that belong to every marketing destination. */
const MARKETING = [
  "marketing",
  "تسويق",
  "ماركتنج",
  "marketing performance",
  "اداء التسويق",
  "أداء التسويق",
];

const MONEY = ["money", "فلوس", "flous", "filos", "مبلغ", "مال", "cash"];

export const SEARCH_DESTINATIONS: SearchDestination[] = [
  {
    id: "overview",
    title: "Overview",
    titleAr: "نظرة عامة",
    route: "/",
    category: "report",
    hint: { ar: "أداء الشركة في الفترة", en: "How the business is doing this period" },
    keywords: [
      "overview",
      "home",
      "dashboard",
      "executive summary",
      "summary",
      "نظرة عامة",
      "الرئيسية",
      "الملخص",
      "ملخص",
      "لوحة",
      "داشبورد",
      "dashbord",
      "nazra",
      "molakhas",
      "kpi",
      "kpis",
      "مؤشرات",
      "الارقام",
      "الأرقام",
      "how are we doing",
      "performance",
      "اداء",
      "أداء",
    ],
  },
  {
    id: "marketing",
    title: "Marketing",
    titleAr: "التسويق",
    route: "/acquisition",
    category: "report",
    hint: { ar: "الإنفاق والعملاء والمبيعات من الإعلانات", en: "Spend, leads and sales from ads" },
    keywords: [
      ...MARKETING,
      "acquisition",
      "acquisition performance",
      "استحواذ",
      "الاستحواذ",
      "ads performance",
      "اداء الاعلانات",
      "roas",
      "عائد",
      "العائد على الانفاق",
      "return on ad spend",
      "cpl",
      "تكلفة العميل",
      "cost per lead",
      "spend",
      "صرف",
      "الصرف",
      "انفاق",
      "الإنفاق",
      "sarf",
      "enfaq",
    ],
  },
  {
    id: "campaigns",
    title: "Campaigns",
    titleAr: "الحملات",
    route: "/campaigns",
    category: "report",
    hint: { ar: "كل حملة: الصرف والعملاء والعائد", en: "Every campaign: spend, leads and return" },
    keywords: [
      ...MARKETING,
      "campaign",
      "campaigns",
      "campain",
      "campagn",
      "campgn",
      "campaings",
      "حملة",
      "حملات",
      "الحملات",
      "hamla",
      "hamlat",
      "7amla",
      "7amlat",
      "اعلان",
      "اعلانات",
      "إعلانات",
      "e3lan",
      "e3lanat",
      "elanat",
      "ads",
      "advertising",
      "best campaigns",
      "worst campaigns",
      "احسن حملة",
      "اسوأ حملة",
      "حملات تحتاج متابعة",
      "needs attention",
      "active campaigns",
      "حملات شغالة",
      "live campaigns",
    ],
  },
  {
    id: "creatives",
    title: "Creatives",
    titleAr: "المواد الإعلانية",
    route: "/acquisition",
    search: { section: "ads", view: "creatives" },
    category: "report",
    hint: { ar: "كل مادة إعلانية ونتائجها", en: "Every creative and what it produced" },
    keywords: [
      ...MARKETING,
      "creative",
      "creatives",
      "creativ",
      "creatve",
      "kreative",
      "كرياتيف",
      "الكرياتيف",
      "مادة اعلانية",
      "المواد الاعلانية",
      "مواد",
      "تصميم",
      "تصاميم",
      "صور الاعلانات",
      "فيديو",
      "video",
      "image",
      "best ads",
      "احسن اعلان",
      "افضل مادة",
      "winning creative",
      "ad content",
      "creative performance",
    ],
  },
  {
    id: "lead-sources",
    title: "Lead sources",
    titleAr: "مصادر العملاء",
    route: "/acquisition",
    search: { section: "leads" },
    category: "report",
    hint: { ar: "من أين جاء العملاء وجودتهم", en: "Where leads came from, and their quality" },
    keywords: [
      "lead source",
      "lead sources",
      "sources",
      "مصادر",
      "مصدر العملاء",
      "مصادر العملاء",
      "masader",
      "lead quality",
      "جودة العملاء",
      "جوده",
      "quality",
      "forms",
      "lead forms",
      "نماذج",
      "نموذج",
      "instant form",
      "namazeg",
      "whatsapp",
      "واتساب",
      "واتس",
      "wa",
      "whatsap",
      "whats app",
      "messenger",
      "ماسنجر",
      "مسنجر",
      "fb messages",
      "facebook messages",
      "instagram",
      "انستجرام",
      "انستغرام",
      "insta",
      "dm",
      "landing",
      "landing page",
      "lp",
      "صفحة هبوط",
      "صفحات الهبوط",
      "hobout",
    ],
  },
  {
    id: "sales-crm",
    title: "Sales & CRM",
    titleAr: "المبيعات والعملاء",
    route: "/leads",
    category: "report",
    hint: { ar: "كل عميل ومرحلته ونتيجته", en: "Every lead, its stage and its outcome" },
    keywords: [
      "leads",
      "lead",
      "crm",
      "customers",
      "clients",
      "عملاء",
      "العملاء",
      "عميل",
      "زباين",
      "زبائن",
      "3omala",
      "omala",
      "leadz",
      "sales",
      "مبيعات",
      "المبيعات",
      "mabe3at",
      "mabeaat",
      "pipeline",
      "خط البيع",
      "stage",
      "مرحلة",
      "المراحل",
      "qualified",
      "مؤهل",
      "مؤهلين",
      "follow up",
      "متابعة",
      "opportunities",
      "فرص",
      "odoo",
      "اودو",
    ],
  },
  {
    id: "lost",
    title: "Lost deals",
    titleAr: "الصفقات المفقودة",
    route: "/lost",
    category: "report",
    hint: { ar: "لماذا خسرنا الصفقات", en: "Why deals were lost" },
    keywords: [
      "lost",
      "lost deals",
      "خسارة",
      "خسائر",
      "مفقود",
      "المفقودة",
      "ضايع",
      "ضائع",
      "khesara",
      "loss reason",
      "سبب الخسارة",
      "rejected",
      "مرفوض",
    ],
  },
  {
    id: "revenue",
    title: "Revenue",
    titleAr: "الإيرادات",
    route: "/accounting",
    category: "report",
    hint: { ar: "التحصيل والفواتير", en: "Collection and invoices" },
    keywords: [
      ...MONEY,
      "revenue",
      "revenu",
      "reveune",
      "income",
      "collection",
      "collections",
      "accounting",
      "accounts",
      "paid",
      "payment",
      "payments",
      "invoice",
      "invoices",
      "ايراد",
      "إيراد",
      "ايرادات",
      "الإيرادات",
      "تحصيل",
      "التحصيل",
      "ta7seel",
      "tahseel",
      "eradat",
      "فاتورة",
      "فواتير",
      "fatora",
      "fawater",
      "مدفوع",
      "مدفوعات",
      "حسابات",
      "الحسابات",
      "hesabat",
    ],
  },
  {
    id: "marketing-revenue",
    title: "Marketing → revenue",
    titleAr: "من التسويق للإيراد",
    route: "/accounting",
    search: { view: "marketing" },
    category: "report",
    hint: { ar: "الإيراد المرتبط بالإعلانات", en: "Revenue linked to advertising" },
    keywords: [
      ...MARKETING,
      ...MONEY,
      "marketing revenue",
      "ad revenue",
      "attributed revenue",
      "الايراد من الاعلانات",
      "ايراد التسويق",
      "الإيراد المرتبط",
      "roas",
      "عائد الإعلانات",
      "sales performance",
      "اداء المبيعات",
      "closed loop",
    ],
  },
  {
    id: "courses",
    title: "Courses",
    titleAr: "الكورسات",
    route: "/courses",
    category: "report",
    hint: { ar: "أداء كل كورس", en: "How each course performs" },
    keywords: [
      "course",
      "courses",
      "product",
      "products",
      "كورس",
      "كورسات",
      "الكورسات",
      "دورة",
      "دورات",
      "kors",
      "kors at",
      "koursat",
      "dawrat",
      "training",
      "تدريب",
      "برنامج",
      "programs",
    ],
  },
  {
    id: "team",
    title: "Team performance",
    titleAr: "أداء الفريق",
    route: "/teams",
    category: "report",
    hint: { ar: "أداء فريق المبيعات", en: "How the sales team performs" },
    keywords: [
      "team",
      "teams",
      "sales team",
      "employees",
      "employee",
      "staff",
      "agents",
      "فريق",
      "الفريق",
      "فرق",
      "موظف",
      "موظفين",
      "مندوب",
      "مندوبين",
      "mandoub",
      "faree2",
      "farek",
      "sales agents",
      "performance",
      "تارجت",
      "target",
    ],
  },
  {
    id: "media-buyers",
    title: "Media buyers",
    titleAr: "الميديا بايرز",
    route: "/media-buyers",
    category: "report",
    hint: { ar: "أداء كل ميديا باير", en: "How each media buyer performs" },
    keywords: [
      "media buyer",
      "media buyers",
      "mediabuyer",
      "buyer",
      "ميديا باير",
      "ميديا بايرز",
      "الميديا",
      "media",
      "sayed",
      "shazly",
      "سيد",
      "شاذلي",
      "من بيشتغل على الحملة",
    ],
  },
  {
    id: "media-plan",
    title: "Media plan",
    titleAr: "الخطة الإعلامية",
    route: "/media-plan",
    category: "report",
    hint: { ar: "الميزانية المخططة مقابل الفعلي", en: "Planned budget against actual" },
    keywords: [
      "media plan",
      "plan",
      "budget",
      "خطة",
      "الخطة",
      "ميزانية",
      "الميزانية",
      "mizaneya",
      "khota",
      "planned spend",
      "الصرف المخطط",
    ],
  },
  {
    id: "landing-pages",
    title: "Landing pages",
    titleAr: "صفحات الهبوط",
    route: "/landing-pages",
    category: "report",
    hint: { ar: "أداء كل صفحة هبوط", en: "How each landing page performs" },
    keywords: [
      "landing",
      "landing page",
      "landing pages",
      "landing pag",
      "lp",
      "صفحة هبوط",
      "صفحات الهبوط",
      "الهبوط",
      "hobot",
      "hobout",
      "website form",
      "form submissions",
      "ارسالات",
    ],
  },
  {
    id: "website",
    title: "Website tracking",
    titleAr: "تتبع الموقع",
    route: "/website",
    category: "report",
    hint: { ar: "زيارات الموقع وتحويلاته", en: "Website visits and conversions" },
    keywords: [
      "website",
      "web",
      "site",
      "موقع",
      "الموقع",
      "mawqe3",
      "traffic",
      "زيارات",
      "sessions",
      "جلسات",
      "conversions",
      "تحويلات",
      "gtm",
      "analytics",
    ],
  },
  {
    id: "attribution",
    title: "Conversation attribution",
    titleAr: "إسناد المحادثات",
    route: "/attribution",
    category: "report",
    hint: { ar: "مصدر كل محادثة", en: "Where each conversation came from" },
    keywords: [
      "attribution",
      "اسناد",
      "إسناد",
      "conversation",
      "conversations",
      "محادثة",
      "محادثات",
      "chat",
      "chatwoot",
      "شات",
      "whatsapp",
      "واتساب",
      "whatsap",
      "wa",
      "messenger",
      "ماسنجر",
      "instagram",
      "انستجرام",
      "referral",
      "ctwa",
      "click to whatsapp",
    ],
  },
  {
    id: "data-coverage",
    title: "Data coverage",
    titleAr: "تغطية البيانات",
    route: "/acquisition",
    search: { section: "coverage" },
    category: "report",
    hint: { ar: "دقة الربط وحالة المصادر", en: "Attribution accuracy and source health" },
    keywords: [
      "coverage",
      "data",
      "data health",
      "تغطية",
      "التغطية",
      "جودة البيانات",
      "صحة البيانات",
      "technical",
      "تقني",
      "diagnostics",
      "تشخيص",
      "matching",
      "مطابقة",
      "sync",
      "مزامنة",
      "webhook",
      "readiness",
    ],
  },
  {
    id: "linked-sales",
    title: "Linked sales records",
    titleAr: "سجلات المبيعات المرتبطة",
    route: "/acquisition",
    search: { section: "sales" },
    category: "report",
    hint: { ar: "كل عميل من إعلانه حتى الفاتورة", en: "Every lead from its ad to its invoice" },
    keywords: [
      "records",
      "سجلات",
      "linked sales",
      "المبيعات المرتبطة",
      "lead to sale",
      "من الاعلان للفاتورة",
      "exact attribution",
      "الاسناد الدقيق",
      "closed loop records",
    ],
  },
  {
    id: "ads-explorer",
    title: "Ads explorer",
    titleAr: "تحليل الإعلانات المتقدم",
    route: "/ads",
    category: "report",
    hint: { ar: "كل المنصات بكل الأعمدة", en: "Every platform, every column" },
    keywords: [
      "ads",
      "ad",
      "explorer",
      "advanced",
      "تحليل",
      "متقدم",
      "اعلانات",
      "الاعلانات",
      "columns",
      "اعمدة",
      "meta",
      "ميتا",
      "snapchat",
      "سناب",
      "tiktok",
      "تيك توك",
      "google",
      "جوجل",
      "platform",
      "منصة",
      "المنصات",
    ],
  },
  {
    id: "pricing",
    title: "Pricing",
    titleAr: "الأسعار",
    route: "/pricing",
    category: "report",
    hint: { ar: "كتالوج الأسعار والعروض", en: "The price book and offers" },
    keywords: [
      "price",
      "pricing",
      "prices",
      "سعر",
      "اسعار",
      "الأسعار",
      "as3ar",
      "عرض",
      "عروض",
      "offers",
      "discount",
      "خصم",
      "price book",
    ],
  },
  {
    id: "social",
    title: "Social media",
    titleAr: "السوشيال ميديا",
    route: "/social-media",
    category: "report",
    hint: { ar: "أداء الصفحات والمحتوى", en: "Page and content performance" },
    keywords: [
      "social",
      "social media",
      "سوشيال",
      "السوشيال",
      "صفحات",
      "facebook",
      "فيسبوك",
      "instagram",
      "انستجرام",
      "followers",
      "متابعين",
      "posts",
      "منشورات",
      "engagement",
      "تفاعل",
    ],
  },
  {
    id: "organic",
    title: "Organic",
    titleAr: "الأورجانيك",
    route: "/organic",
    category: "report",
    hint: { ar: "عملاء ومبيعات بدون إعلان", en: "Leads and sales without ads" },
    keywords: [
      "organic",
      "اورجانيك",
      "أورجانيك",
      "غير مدفوع",
      "بدون اعلان",
      "free leads",
      "referral",
      "ترشيحات",
      "word of mouth",
    ],
  },
  {
    id: "weekend",
    title: "Weekend comparison",
    titleAr: "مقارنة الويك إند",
    route: "/weekend",
    category: "report",
    hint: { ar: "الويك إند مقابل أيام الأسبوع", en: "Weekend against weekdays" },
    keywords: [
      "weekend",
      "ويك اند",
      "الويك إند",
      "الاجازة",
      "اجازة",
      "friday",
      "جمعة",
      "saturday",
      "سبت",
      "weekday",
      "ايام الاسبوع",
      "comparison",
      "مقارنة",
    ],
  },
  {
    id: "yoy",
    title: "Year on year",
    titleAr: "سنة بسنة",
    route: "/yoy",
    category: "report",
    hint: { ar: "نفس الفترة من السنة الماضية", en: "The same period last year" },
    keywords: [
      "yoy",
      "year on year",
      "سنة بسنة",
      "السنة الماضية",
      "last year",
      "مقارنة سنوية",
      "annual",
      "سنوي",
      "growth",
      "نمو",
    ],
  },
  {
    id: "guide",
    title: "User guide",
    titleAr: "دليل الاستخدام",
    route: "/guide",
    category: "report",
    hint: { ar: "كيف تقرأ الداشبورد", en: "How to read the dashboard" },
    keywords: [
      "guide",
      "help",
      "how to",
      "دليل",
      "مساعدة",
      "شرح",
      "ازاي",
      "كيف",
      "documentation",
      "منين الرقم",
      "where does this number come from",
    ],
  },
];
