/**
 * Customer entry-month revenue cohorts.
 *
 * "For the customers who entered in each month, how many invoices did they
 * eventually produce and how much paid revenue?"
 *
 * This is a different question from monthly collections, and the two are
 * labelled apart everywhere:
 *
 *   Revenue collected in this month     paid invoice lines dated by Payment Date
 *   Revenue generated by customers who  paid invoice lines at ANY payment date up
 *   entered in this month               to the as-of date, credited to the month
 *                                       the CRM record was created
 *
 * The join is deterministic and nothing else: Accounting line `Sales Order #`
 * → `crm_sale_order_links` (Odoo sale.order.opportunity_id) → CRM record →
 * CRM creation date. No customer-name, phone or partner matching. Money comes
 * only from Accounting (the financial authority); a line that cannot be linked
 * is reported as unlinked, never dropped.
 */

export interface CohortCrmLead {
  id: string;
  /** `YYYY-MM-DD` Cairo creation date. */
  createdAt: string;
  won: boolean;
}

export interface CohortInvoiceLine {
  orderRef: string;
  movement: string;
  /** Signed USD from the Accounting authority (credit notes are negative). */
  usdPaid: number;
  paymentDate: string;
  invoiceDate: string;
  isCreditNote: boolean;
}

export interface OrderOpportunityLink {
  orderName: string;
  opportunityId: string;
}

export interface EntryMonthCohortRow {
  /** `YYYY-MM` of CRM creation. */
  entryMonth: string;
  uniqueLeads: number;
  won: number;
  customersWithPaidInvoice: number;
  distinctPaidInvoices: number;
  creditNotes: number;
  paidRevenue: number;
  /** Customers with a paid invoice ÷ unique leads, 0–100. */
  invoiceConversionRate: number | null;
  /** Paid revenue ÷ customers with a paid invoice. */
  averagePaidRevenuePerCustomer: number | null;
  /** Days from CRM creation to first payment, over customers with a non-negative lag. */
  averageDaysToFirstInvoice: number | null;
  medianDaysToFirstInvoice: number | null;
  /** Customers whose first payment predates the CRM record (a re-created record). */
  paidBeforeCreation: number;
}

export interface EntryMonthCohortResult {
  asOf: string;
  window: { from: string; to: string };
  rows: EntryMonthCohortRow[];
  totals: Omit<EntryMonthCohortRow, "entryMonth">;
  /**
   * Every Accounting line paid up to `asOf`, split so the parts always add up:
   * total = cohortRevenue + otherCohortsRevenue + linkedUnknownCrmRevenue + unlinkedRevenue.
   */
  reconciliation: {
    totalAccountingRevenue: number;
    cohortRevenue: number;
    otherCohortsRevenue: number;
    linkedUnknownCrmRevenue: number;
    unlinkedRevenue: number;
    linkedShare: number | null;
    lines: number;
    unlinkedLines: number;
  };
}

const round2 = (value: number) => Math.round(value * 100) / 100;
const month = (date: string) => (/^\d{4}-\d{2}/.test(date) ? date.slice(0, 7) : "");
const lineDate = (line: CohortInvoiceLine) =>
  (line.isCreditNote ? line.invoiceDate || line.paymentDate : line.paymentDate).slice(0, 10);

function daysBetween(from: string, to: string): number | null {
  const start = Date.parse(`${from.slice(0, 10)}T00:00:00Z`);
  const end = Date.parse(`${to.slice(0, 10)}T00:00:00Z`);
  return Number.isFinite(start) && Number.isFinite(end) ? Math.round((end - start) / 86_400_000) : null;
}

function median(values: number[]): number | null {
  if (!values.length) return null;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2;
}

interface MutableCohort {
  entryMonth: string;
  leads: Set<string>;
  won: Set<string>;
  paidCustomers: Set<string>;
  invoices: Set<string>;
  creditNotes: Set<string>;
  revenue: number;
  lags: number[];
  paidBeforeCreation: number;
}

function finish(cohort: MutableCohort): EntryMonthCohortRow {
  const customers = cohort.paidCustomers.size;
  const nonNegative = cohort.lags.filter((lag) => lag >= 0);
  return {
    entryMonth: cohort.entryMonth,
    uniqueLeads: cohort.leads.size,
    won: cohort.won.size,
    customersWithPaidInvoice: customers,
    distinctPaidInvoices: cohort.invoices.size,
    creditNotes: cohort.creditNotes.size,
    paidRevenue: round2(cohort.revenue),
    invoiceConversionRate: cohort.leads.size ? (customers / cohort.leads.size) * 100 : null,
    averagePaidRevenuePerCustomer: customers ? round2(cohort.revenue / customers) : null,
    averageDaysToFirstInvoice: nonNegative.length
      ? Math.round((nonNegative.reduce((sum, lag) => sum + lag, 0) / nonNegative.length) * 10) / 10
      : null,
    medianDaysToFirstInvoice: median(nonNegative),
    paidBeforeCreation: cohort.paidBeforeCreation,
  };
}

export function buildEntryMonthCohorts(input: {
  leads: readonly CohortCrmLead[];
  lines: readonly CohortInvoiceLine[];
  links: readonly OrderOpportunityLink[];
  window: { from: string; to: string };
  asOf: string;
}): EntryMonthCohortResult {
  const { window, asOf } = input;
  const inWindow = (date: string) =>
    Boolean(date) && (!window.from || date >= window.from) && (!window.to || date <= window.to);

  const leadById = new Map<string, CohortCrmLead>();
  for (const lead of input.leads) if (lead.id && !leadById.has(lead.id)) leadById.set(lead.id, lead);
  const opportunityByOrder = new Map<string, string>();
  const ambiguousOrders = new Set<string>();
  for (const link of input.links) {
    const order = link.orderName.trim();
    if (!order || !link.opportunityId) continue;
    const existing = opportunityByOrder.get(order);
    if (existing && existing !== link.opportunityId) ambiguousOrders.add(order);
    else opportunityByOrder.set(order, link.opportunityId);
  }
  // An order name that resolves to two opportunities is not a deterministic link.
  for (const order of ambiguousOrders) opportunityByOrder.delete(order);

  const cohorts = new Map<string, MutableCohort>();
  const cohortOf = (entryMonth: string) => {
    let cohort = cohorts.get(entryMonth);
    if (!cohort) {
      cohort = {
        entryMonth,
        leads: new Set(),
        won: new Set(),
        paidCustomers: new Set(),
        invoices: new Set(),
        creditNotes: new Set(),
        revenue: 0,
        lags: [],
        paidBeforeCreation: 0,
      };
      cohorts.set(entryMonth, cohort);
    }
    return cohort;
  };
  for (const lead of leadById.values()) {
    if (!inWindow(lead.createdAt.slice(0, 10))) continue;
    const cohort = cohortOf(month(lead.createdAt));
    cohort.leads.add(lead.id);
    if (lead.won) cohort.won.add(lead.id);
  }

  const reconciliation = {
    totalAccountingRevenue: 0,
    cohortRevenue: 0,
    otherCohortsRevenue: 0,
    linkedUnknownCrmRevenue: 0,
    unlinkedRevenue: 0,
    linkedShare: null as number | null,
    lines: 0,
    unlinkedLines: 0,
  };
  const firstPayment = new Map<string, string>();
  for (const line of input.lines) {
    const date = lineDate(line);
    if (!date || (asOf && date > asOf)) continue;
    reconciliation.lines += 1;
    reconciliation.totalAccountingRevenue += line.usdPaid;
    const opportunityId = opportunityByOrder.get(line.orderRef.trim());
    if (!opportunityId) {
      reconciliation.unlinkedRevenue += line.usdPaid;
      reconciliation.unlinkedLines += 1;
      continue;
    }
    const lead = leadById.get(opportunityId);
    if (!lead) {
      reconciliation.linkedUnknownCrmRevenue += line.usdPaid;
      continue;
    }
    if (!inWindow(lead.createdAt.slice(0, 10))) {
      reconciliation.otherCohortsRevenue += line.usdPaid;
      continue;
    }
    reconciliation.cohortRevenue += line.usdPaid;
    const cohort = cohortOf(month(lead.createdAt));
    cohort.revenue += line.usdPaid;
    if (line.isCreditNote) {
      if (line.movement) cohort.creditNotes.add(line.movement);
      continue;
    }
    cohort.paidCustomers.add(lead.id);
    if (line.movement) cohort.invoices.add(line.movement);
    const previous = firstPayment.get(lead.id);
    if (!previous || date < previous) firstPayment.set(lead.id, date);
  }
  for (const [leadId, date] of firstPayment) {
    const lead = leadById.get(leadId)!;
    const lag = daysBetween(lead.createdAt, date);
    if (lag === null) continue;
    const cohort = cohortOf(month(lead.createdAt));
    cohort.lags.push(lag);
    if (lag < 0) cohort.paidBeforeCreation += 1;
  }

  for (const key of [
    "totalAccountingRevenue",
    "cohortRevenue",
    "otherCohortsRevenue",
    "linkedUnknownCrmRevenue",
    "unlinkedRevenue",
  ] as const) {
    reconciliation[key] = round2(reconciliation[key]);
  }
  reconciliation.linkedShare = reconciliation.totalAccountingRevenue
    ? ((reconciliation.totalAccountingRevenue - reconciliation.unlinkedRevenue) /
        reconciliation.totalAccountingRevenue) *
      100
    : null;

  const rows = [...cohorts.values()]
    .map(finish)
    .sort((a, b) => a.entryMonth.localeCompare(b.entryMonth));
  const all: MutableCohort = {
    entryMonth: "",
    leads: new Set(),
    won: new Set(),
    paidCustomers: new Set(),
    invoices: new Set(),
    creditNotes: new Set(),
    revenue: 0,
    lags: [],
    paidBeforeCreation: 0,
  };
  for (const cohort of cohorts.values()) {
    cohort.leads.forEach((id) => all.leads.add(id));
    cohort.won.forEach((id) => all.won.add(id));
    cohort.paidCustomers.forEach((id) => all.paidCustomers.add(id));
    cohort.invoices.forEach((id) => all.invoices.add(id));
    cohort.creditNotes.forEach((id) => all.creditNotes.add(id));
    all.revenue += cohort.revenue;
    all.lags.push(...cohort.lags);
    all.paidBeforeCreation += cohort.paidBeforeCreation;
  }
  const { entryMonth: _entryMonth, ...totals } = finish(all);
  return { asOf, window, rows, totals, reconciliation };
}
