import { createFileRoute } from "@tanstack/react-router";

/**
 * Customer entry-month revenue cohorts (see `revenue-cohort.ts`).
 *
 * The window selects which CRM creation months are cohorts. Revenue is every
 * paid Accounting line up to today, linked through the exact
 * sale order → opportunity relation. Dimension filters other than company are
 * not applied: a cohort is a CRM population, and narrowing its money by an ad
 * dimension would silently change the denominator. They are listed back in
 * `ignoredFilters`.
 */
export const Route = createFileRoute("/api/revenue-cohorts")({
  server: {
    handlers: {
      GET: async ({ request }) => {
        const { parseFilters, json } = await import("@/lib/api.server");
        const { loadAllData } = await import("@/lib/sheet-cache.server");
        const { accountingUsdPaid, fxRatesFromFilters } = await import("@/lib/fx-rates");
        const { buildEntryMonthCohorts } = await import("@/lib/revenue-cohort");
        const { METRIC_CONTRACTS } = await import("@/lib/metric-contracts");
        const { acquisitionDatabaseConfigured, getPool, BUSINESS_TIME_ZONE } =
          await import("@/lib/acquisition-attribution.server");

        const filters = await parseFilters(request);
        const snapshot = await loadAllData();
        const fx = fxRatesFromFilters(filters);
        const asOf = new Intl.DateTimeFormat("en-CA", {
          timeZone: BUSINESS_TIME_ZONE,
          year: "numeric",
          month: "2-digit",
          day: "2-digit",
        }).format(new Date());
        const window = {
          from: filters.from || (snapshot.crm.map((row) => row.createdAt).filter(Boolean).sort()[0] ?? ""),
          to: filters.to || asOf,
        };

        let links: { orderName: string; opportunityId: string }[] = [];
        let linksAvailable = false;
        let linksRefreshedAt: string | null = null;
        if (acquisitionDatabaseConfigured()) {
          try {
            const result = await getPool().query<Record<string, unknown>>(
              `SELECT sale_order_name, opportunity_id, max(refreshed_at) OVER () AS refreshed_at
                 FROM crm_sale_order_links`,
            );
            links = result.rows.map((row) => ({
              orderName: String(row.sale_order_name ?? ""),
              opportunityId: String(row.opportunity_id ?? ""),
            }));
            linksAvailable = links.length > 0;
            const refreshed = result.rows[0]?.refreshed_at;
            linksRefreshedAt = refreshed instanceof Date ? refreshed.toISOString() : refreshed ? String(refreshed) : null;
          } catch {
            linksAvailable = false;
          }
        }

        const leads = [
          ...snapshot.crm.map((row) => ({ id: row.id, createdAt: row.createdAt, won: row.isWon })),
          ...snapshot.lost.map((row) => ({ id: row.id, createdAt: row.createdAt, won: false })),
        ];
        const lines = snapshot.accounting
          .filter((row) => !filters.company || row.company === filters.company)
          .map((row) => ({
            orderRef: row.orderRef,
            movement: row.movement,
            usdPaid: accountingUsdPaid(row, fx),
            paymentDate: row.paymentDate,
            invoiceDate: row.invoiceDate,
            isCreditNote: row.isCreditNote,
          }));

        const result = linksAvailable
          ? buildEntryMonthCohorts({ leads, lines, links, window, asOf })
          : null;
        const ignoredFilters = (
          ["platform", "channel", "campaign", "adset", "ad", "source", "course", "salesTeam", "salesperson"] as const
        ).filter((key) => Boolean(filters[key]));

        return json({
          ok: true,
          available: Boolean(result),
          reason: result ? null : "crm_sale_order_links is empty or unavailable",
          linksRefreshedAt,
          ...(result ?? { asOf, window, rows: [], totals: null, reconciliation: null }),
          ignoredFilters,
          fxRates: fx,
          contract: METRIC_CONTRACTS.entryMonthCohortRevenue,
          labels: {
            collected: { en: "Revenue collected in this month", ar: "الإيراد المحصَّل في هذا الشهر" },
            generated: {
              en: "Revenue generated by customers who entered in this month",
              ar: "الإيراد الناتج من العملاء الذين دخلوا في هذا الشهر",
            },
          },
          health: snapshot.health,
        });
      },
    },
  },
});
