/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FullInvoicedRouteImport } from './routes/full-invoiced'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LostRouteImport } from './routes/lost'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCoursesRouteImport } from './routes/api/courses'
import { Route as ApiFiltersRouteImport } from './routes/api/filters'
import { Route as ApiFullInvoicedRouteImport } from './routes/api/full-invoiced'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiLostRouteImport } from './routes/api/lost'
import { Route as ApiMetaRouteImport } from './routes/api/meta'
import { Route as ApiOverviewRouteImport } from './routes/api/overview'
import { Route as ApiRefreshRouteImport } from './routes/api/refresh'
import { Route as ApiSalesRouteImport } from './routes/api/sales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FullInvoicedRoute = FullInvoicedRouteImport.update({
  id: '/full-invoiced',
  path: '/full-invoiced',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesRoute = ApiCoursesRouteImport.update({
  id: '/api/courses',
  path: '/api/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFiltersRoute = ApiFiltersRouteImport.update({
  id: '/api/filters',
  path: '/api/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFullInvoicedRoute = ApiFullInvoicedRouteImport.update({
  id: '/api/full-invoiced',
  path: '/api/full-invoiced',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLostRoute = ApiLostRouteImport.update({
  id: '/api/lost',
  path: '/api/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaRoute = ApiMetaRouteImport.update({
  id: '/api/meta',
  path: '/api/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverviewRoute = ApiOverviewRouteImport.update({
  id: '/api/overview',
  path: '/api/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefreshRoute = ApiRefreshRouteImport.update({
  id: '/api/refresh',
  path: '/api/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesRoute = ApiSalesRouteImport.update({
  id: '/api/sales',
  path: '/api/sales',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/courses': typeof CoursesRoute
  '/full-invoiced': typeof FullInvoicedRoute
  '/leads': typeof LeadsRoute
  '/lost': typeof LostRoute
  '/meta': typeof MetaRoute
  '/sales': typeof SalesRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/filters': typeof ApiFiltersRoute
  '/api/full-invoiced': typeof ApiFullInvoicedRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lost': typeof ApiLostRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/refresh': typeof ApiRefreshRoute
  '/api/sales': typeof ApiSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/courses': typeof CoursesRoute
  '/full-invoiced': typeof FullInvoicedRoute
  '/leads': typeof LeadsRoute
  '/lost': typeof LostRoute
  '/meta': typeof MetaRoute
  '/sales': typeof SalesRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/filters': typeof ApiFiltersRoute
  '/api/full-invoiced': typeof ApiFullInvoicedRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lost': typeof ApiLostRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/refresh': typeof ApiRefreshRoute
  '/api/sales': typeof ApiSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/courses': typeof CoursesRoute
  '/full-invoiced': typeof FullInvoicedRoute
  '/leads': typeof LeadsRoute
  '/lost': typeof LostRoute
  '/meta': typeof MetaRoute
  '/sales': typeof SalesRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/filters': typeof ApiFiltersRoute
  '/api/full-invoiced': typeof ApiFullInvoicedRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lost': typeof ApiLostRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/refresh': typeof ApiRefreshRoute
  '/api/sales': typeof ApiSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/courses'
    | '/full-invoiced'
    | '/leads'
    | '/lost'
    | '/meta'
    | '/sales'
    | '/api/campaigns'
    | '/api/chat'
    | '/api/courses'
    | '/api/filters'
    | '/api/full-invoiced'
    | '/api/leads'
    | '/api/lost'
    | '/api/meta'
    | '/api/overview'
    | '/api/refresh'
    | '/api/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/courses'
    | '/full-invoiced'
    | '/leads'
    | '/lost'
    | '/meta'
    | '/sales'
    | '/api/campaigns'
    | '/api/chat'
    | '/api/courses'
    | '/api/filters'
    | '/api/full-invoiced'
    | '/api/leads'
    | '/api/lost'
    | '/api/meta'
    | '/api/overview'
    | '/api/refresh'
    | '/api/sales'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/courses'
    | '/full-invoiced'
    | '/leads'
    | '/lost'
    | '/meta'
    | '/sales'
    | '/api/campaigns'
    | '/api/chat'
    | '/api/courses'
    | '/api/filters'
    | '/api/full-invoiced'
    | '/api/leads'
    | '/api/lost'
    | '/api/meta'
    | '/api/overview'
    | '/api/refresh'
    | '/api/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  CoursesRoute: typeof CoursesRoute
  FullInvoicedRoute: typeof FullInvoicedRoute
  LeadsRoute: typeof LeadsRoute
  LostRoute: typeof LostRoute
  MetaRoute: typeof MetaRoute
  SalesRoute: typeof SalesRoute
  ApiCampaignsRoute: typeof ApiCampaignsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCoursesRoute: typeof ApiCoursesRoute
  ApiFiltersRoute: typeof ApiFiltersRoute
  ApiFullInvoicedRoute: typeof ApiFullInvoicedRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiLostRoute: typeof ApiLostRoute
  ApiMetaRoute: typeof ApiMetaRoute
  ApiOverviewRoute: typeof ApiOverviewRoute
  ApiRefreshRoute: typeof ApiRefreshRoute
  ApiSalesRoute: typeof ApiSalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-invoiced': {
      id: '/full-invoiced'
      path: '/full-invoiced'
      fullPath: '/full-invoiced'
      preLoaderRoute: typeof FullInvoicedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses': {
      id: '/api/courses'
      path: '/api/courses'
      fullPath: '/api/courses'
      preLoaderRoute: typeof ApiCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/filters': {
      id: '/api/filters'
      path: '/api/filters'
      fullPath: '/api/filters'
      preLoaderRoute: typeof ApiFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/full-invoiced': {
      id: '/api/full-invoiced'
      path: '/api/full-invoiced'
      fullPath: '/api/full-invoiced'
      preLoaderRoute: typeof ApiFullInvoicedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lost': {
      id: '/api/lost'
      path: '/api/lost'
      fullPath: '/api/lost'
      preLoaderRoute: typeof ApiLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta': {
      id: '/api/meta'
      path: '/api/meta'
      fullPath: '/api/meta'
      preLoaderRoute: typeof ApiMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overview': {
      id: '/api/overview'
      path: '/api/overview'
      fullPath: '/api/overview'
      preLoaderRoute: typeof ApiOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refresh': {
      id: '/api/refresh'
      path: '/api/refresh'
      fullPath: '/api/refresh'
      preLoaderRoute: typeof ApiRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales': {
      id: '/api/sales'
      path: '/api/sales'
      fullPath: '/api/sales'
      preLoaderRoute: typeof ApiSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  CoursesRoute: CoursesRoute,
  FullInvoicedRoute: FullInvoicedRoute,
  LeadsRoute: LeadsRoute,
  LostRoute: LostRoute,
  MetaRoute: MetaRoute,
  SalesRoute: SalesRoute,
  ApiCampaignsRoute: ApiCampaignsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCoursesRoute: ApiCoursesRoute,
  ApiFiltersRoute: ApiFiltersRoute,
  ApiFullInvoicedRoute: ApiFullInvoicedRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiLostRoute: ApiLostRoute,
  ApiMetaRoute: ApiMetaRoute,
  ApiOverviewRoute: ApiOverviewRoute,
  ApiRefreshRoute: ApiRefreshRoute,
  ApiSalesRoute: ApiSalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
