/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FullInvoicedRouteImport } from './routes/full-invoiced'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LostRouteImport } from './routes/lost'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as YoyRouteImport } from './routes/yoy'
import { Route as ApiAdsRouteImport } from './routes/api/ads'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCoursesRouteImport } from './routes/api/courses'
import { Route as ApiFiltersRouteImport } from './routes/api/filters'
import { Route as ApiFullInvoicedRouteImport } from './routes/api/full-invoiced'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiLostRouteImport } from './routes/api/lost'
import { Route as ApiOverviewRouteImport } from './routes/api/overview'
import { Route as ApiRefreshRouteImport } from './routes/api/refresh'
import { Route as ApiSalesRouteImport } from './routes/api/sales'
import { Route as ApiTeamsRouteImport } from './routes/api/teams'
import { Route as ApiWebsiteRouteImport } from './routes/api/website'
import { Route as ApiYoyRouteImport } from './routes/api/yoy'
import { Route as ApiTelegramPreviewRouteImport } from './routes/api/telegram.preview'
import { Route as ApiTelegramSendDailyRouteImport } from './routes/api/telegram.send-daily'
import { Route as ApiTelegramSetupRouteImport } from './routes/api/telegram.setup'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FullInvoicedRoute = FullInvoicedRouteImport.update({
  id: '/full-invoiced',
  path: '/full-invoiced',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const YoyRoute = YoyRouteImport.update({
  id: '/yoy',
  path: '/yoy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsRoute = ApiAdsRouteImport.update({
  id: '/api/ads',
  path: '/api/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesRoute = ApiCoursesRouteImport.update({
  id: '/api/courses',
  path: '/api/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFiltersRoute = ApiFiltersRouteImport.update({
  id: '/api/filters',
  path: '/api/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFullInvoicedRoute = ApiFullInvoicedRouteImport.update({
  id: '/api/full-invoiced',
  path: '/api/full-invoiced',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLostRoute = ApiLostRouteImport.update({
  id: '/api/lost',
  path: '/api/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverviewRoute = ApiOverviewRouteImport.update({
  id: '/api/overview',
  path: '/api/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefreshRoute = ApiRefreshRouteImport.update({
  id: '/api/refresh',
  path: '/api/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesRoute = ApiSalesRouteImport.update({
  id: '/api/sales',
  path: '/api/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsRoute = ApiTeamsRouteImport.update({
  id: '/api/teams',
  path: '/api/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebsiteRoute = ApiWebsiteRouteImport.update({
  id: '/api/website',
  path: '/api/website',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoyRoute = ApiYoyRouteImport.update({
  id: '/api/yoy',
  path: '/api/yoy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramPreviewRoute = ApiTelegramPreviewRouteImport.update({
  id: '/api/telegram/preview',
  path: '/api/telegram/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSendDailyRoute = ApiTelegramSendDailyRouteImport.update({
  id: '/api/telegram/send-daily',
  path: '/api/telegram/send-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSetupRoute = ApiTelegramSetupRouteImport.update({
  id: '/api/telegram/setup',
  path: '/api/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/campaigns': typeof CampaignsRoute
  '/courses': typeof CoursesRoute
  '/full-invoiced': typeof FullInvoicedRoute
  '/leads': typeof LeadsRoute
  '/lost': typeof LostRoute
  '/sales': typeof SalesRoute
  '/teams': typeof TeamsRoute
  '/website': typeof WebsiteRoute
  '/yoy': typeof YoyRoute
  '/api/ads': typeof ApiAdsRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/filters': typeof ApiFiltersRoute
  '/api/full-invoiced': typeof ApiFullInvoicedRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lost': typeof ApiLostRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/refresh': typeof ApiRefreshRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/website': typeof ApiWebsiteRoute
  '/api/yoy': typeof ApiYoyRoute
  '/api/telegram/preview': typeof ApiTelegramPreviewRoute
  '/api/telegram/send-daily': typeof ApiTelegramSendDailyRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/campaigns': typeof CampaignsRoute
  '/courses': typeof CoursesRoute
  '/full-invoiced': typeof FullInvoicedRoute
  '/leads': typeof LeadsRoute
  '/lost': typeof LostRoute
  '/sales': typeof SalesRoute
  '/teams': typeof TeamsRoute
  '/website': typeof WebsiteRoute
  '/yoy': typeof YoyRoute
  '/api/ads': typeof ApiAdsRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/filters': typeof ApiFiltersRoute
  '/api/full-invoiced': typeof ApiFullInvoicedRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lost': typeof ApiLostRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/refresh': typeof ApiRefreshRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/website': typeof ApiWebsiteRoute
  '/api/yoy': typeof ApiYoyRoute
  '/api/telegram/preview': typeof ApiTelegramPreviewRoute
  '/api/telegram/send-daily': typeof ApiTelegramSendDailyRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/campaigns': typeof CampaignsRoute
  '/courses': typeof CoursesRoute
  '/full-invoiced': typeof FullInvoicedRoute
  '/leads': typeof LeadsRoute
  '/lost': typeof LostRoute
  '/sales': typeof SalesRoute
  '/teams': typeof TeamsRoute
  '/website': typeof WebsiteRoute
  '/yoy': typeof YoyRoute
  '/api/ads': typeof ApiAdsRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/filters': typeof ApiFiltersRoute
  '/api/full-invoiced': typeof ApiFullInvoicedRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lost': typeof ApiLostRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/refresh': typeof ApiRefreshRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/website': typeof ApiWebsiteRoute
  '/api/yoy': typeof ApiYoyRoute
  '/api/telegram/preview': typeof ApiTelegramPreviewRoute
  '/api/telegram/send-daily': typeof ApiTelegramSendDailyRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/campaigns'
    | '/courses'
    | '/full-invoiced'
    | '/leads'
    | '/lost'
    | '/sales'
    | '/teams'
    | '/website'
    | '/yoy'
    | '/api/ads'
    | '/api/campaigns'
    | '/api/chat'
    | '/api/courses'
    | '/api/filters'
    | '/api/full-invoiced'
    | '/api/leads'
    | '/api/lost'
    | '/api/overview'
    | '/api/refresh'
    | '/api/sales'
    | '/api/teams'
    | '/api/website'
    | '/api/yoy'
    | '/api/telegram/preview'
    | '/api/telegram/send-daily'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/campaigns'
    | '/courses'
    | '/full-invoiced'
    | '/leads'
    | '/lost'
    | '/sales'
    | '/teams'
    | '/website'
    | '/yoy'
    | '/api/ads'
    | '/api/campaigns'
    | '/api/chat'
    | '/api/courses'
    | '/api/filters'
    | '/api/full-invoiced'
    | '/api/leads'
    | '/api/lost'
    | '/api/overview'
    | '/api/refresh'
    | '/api/sales'
    | '/api/teams'
    | '/api/website'
    | '/api/yoy'
    | '/api/telegram/preview'
    | '/api/telegram/send-daily'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/campaigns'
    | '/courses'
    | '/full-invoiced'
    | '/leads'
    | '/lost'
    | '/sales'
    | '/teams'
    | '/website'
    | '/yoy'
    | '/api/ads'
    | '/api/campaigns'
    | '/api/chat'
    | '/api/courses'
    | '/api/filters'
    | '/api/full-invoiced'
    | '/api/leads'
    | '/api/lost'
    | '/api/overview'
    | '/api/refresh'
    | '/api/sales'
    | '/api/teams'
    | '/api/website'
    | '/api/yoy'
    | '/api/telegram/preview'
    | '/api/telegram/send-daily'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  CampaignsRoute: typeof CampaignsRoute
  CoursesRoute: typeof CoursesRoute
  FullInvoicedRoute: typeof FullInvoicedRoute
  LeadsRoute: typeof LeadsRoute
  LostRoute: typeof LostRoute
  SalesRoute: typeof SalesRoute
  TeamsRoute: typeof TeamsRoute
  WebsiteRoute: typeof WebsiteRoute
  YoyRoute: typeof YoyRoute
  ApiAdsRoute: typeof ApiAdsRoute
  ApiCampaignsRoute: typeof ApiCampaignsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCoursesRoute: typeof ApiCoursesRoute
  ApiFiltersRoute: typeof ApiFiltersRoute
  ApiFullInvoicedRoute: typeof ApiFullInvoicedRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiLostRoute: typeof ApiLostRoute
  ApiOverviewRoute: typeof ApiOverviewRoute
  ApiRefreshRoute: typeof ApiRefreshRoute
  ApiSalesRoute: typeof ApiSalesRoute
  ApiTeamsRoute: typeof ApiTeamsRoute
  ApiWebsiteRoute: typeof ApiWebsiteRoute
  ApiYoyRoute: typeof ApiYoyRoute
  ApiTelegramPreviewRoute: typeof ApiTelegramPreviewRoute
  ApiTelegramSendDailyRoute: typeof ApiTelegramSendDailyRoute
  ApiTelegramSetupRoute: typeof ApiTelegramSetupRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-invoiced': {
      id: '/full-invoiced'
      path: '/full-invoiced'
      fullPath: '/full-invoiced'
      preLoaderRoute: typeof FullInvoicedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoy': {
      id: '/yoy'
      path: '/yoy'
      fullPath: '/yoy'
      preLoaderRoute: typeof YoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads': {
      id: '/api/ads'
      path: '/api/ads'
      fullPath: '/api/ads'
      preLoaderRoute: typeof ApiAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses': {
      id: '/api/courses'
      path: '/api/courses'
      fullPath: '/api/courses'
      preLoaderRoute: typeof ApiCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/filters': {
      id: '/api/filters'
      path: '/api/filters'
      fullPath: '/api/filters'
      preLoaderRoute: typeof ApiFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/full-invoiced': {
      id: '/api/full-invoiced'
      path: '/api/full-invoiced'
      fullPath: '/api/full-invoiced'
      preLoaderRoute: typeof ApiFullInvoicedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lost': {
      id: '/api/lost'
      path: '/api/lost'
      fullPath: '/api/lost'
      preLoaderRoute: typeof ApiLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overview': {
      id: '/api/overview'
      path: '/api/overview'
      fullPath: '/api/overview'
      preLoaderRoute: typeof ApiOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refresh': {
      id: '/api/refresh'
      path: '/api/refresh'
      fullPath: '/api/refresh'
      preLoaderRoute: typeof ApiRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales': {
      id: '/api/sales'
      path: '/api/sales'
      fullPath: '/api/sales'
      preLoaderRoute: typeof ApiSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams': {
      id: '/api/teams'
      path: '/api/teams'
      fullPath: '/api/teams'
      preLoaderRoute: typeof ApiTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/website': {
      id: '/api/website'
      path: '/api/website'
      fullPath: '/api/website'
      preLoaderRoute: typeof ApiWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yoy': {
      id: '/api/yoy'
      path: '/api/yoy'
      fullPath: '/api/yoy'
      preLoaderRoute: typeof ApiYoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/preview': {
      id: '/api/telegram/preview'
      path: '/api/telegram/preview'
      fullPath: '/api/telegram/preview'
      preLoaderRoute: typeof ApiTelegramPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/send-daily': {
      id: '/api/telegram/send-daily'
      path: '/api/telegram/send-daily'
      fullPath: '/api/telegram/send-daily'
      preLoaderRoute: typeof ApiTelegramSendDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/setup': {
      id: '/api/telegram/setup'
      path: '/api/telegram/setup'
      fullPath: '/api/telegram/setup'
      preLoaderRoute: typeof ApiTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  CampaignsRoute: CampaignsRoute,
  CoursesRoute: CoursesRoute,
  FullInvoicedRoute: FullInvoicedRoute,
  LeadsRoute: LeadsRoute,
  LostRoute: LostRoute,
  SalesRoute: SalesRoute,
  TeamsRoute: TeamsRoute,
  WebsiteRoute: WebsiteRoute,
  YoyRoute: YoyRoute,
  ApiAdsRoute: ApiAdsRoute,
  ApiCampaignsRoute: ApiCampaignsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCoursesRoute: ApiCoursesRoute,
  ApiFiltersRoute: ApiFiltersRoute,
  ApiFullInvoicedRoute: ApiFullInvoicedRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiLostRoute: ApiLostRoute,
  ApiOverviewRoute: ApiOverviewRoute,
  ApiRefreshRoute: ApiRefreshRoute,
  ApiSalesRoute: ApiSalesRoute,
  ApiTeamsRoute: ApiTeamsRoute,
  ApiWebsiteRoute: ApiWebsiteRoute,
  ApiYoyRoute: ApiYoyRoute,
  ApiTelegramPreviewRoute: ApiTelegramPreviewRoute,
  ApiTelegramSendDailyRoute: ApiTelegramSendDailyRoute,
  ApiTelegramSetupRoute: ApiTelegramSetupRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
