/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FullInvoicedRouteImport } from './routes/full-invoiced'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LostRouteImport } from './routes/lost'
import { Route as MediaBuyersRouteImport } from './routes/media-buyers'
import { Route as MediaPlanRouteImport } from './routes/media-plan'
import { Route as OrganicRouteImport } from './routes/organic'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as WeekendRouteImport } from './routes/weekend'
import { Route as YoyRouteImport } from './routes/yoy'
import { Route as ApiAccountingRouteImport } from './routes/api/accounting'
import { Route as ApiAccountingExportRouteImport } from './routes/api/accounting-export'
import { Route as ApiAdsRouteImport } from './routes/api/ads'
import { Route as ApiAgentCourseInvoicesRouteImport } from './routes/api/agent-course-invoices'
import { Route as ApiCampaignRiskRouteImport } from './routes/api/campaign-risk'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCourseLeadAlertsRouteImport } from './routes/api/course-lead-alerts'
import { Route as ApiCoursesRouteImport } from './routes/api/courses'
import { Route as ApiEmployeeCallDetailRouteImport } from './routes/api/employee-call-detail'
import { Route as ApiEmployeeCallRecordingRouteImport } from './routes/api/employee-call-recording'
import { Route as ApiEmployeeCallsRouteImport } from './routes/api/employee-calls'
import { Route as ApiEmployeeEvidenceRouteImport } from './routes/api/employee-evidence'
import { Route as ApiFiltersRouteImport } from './routes/api/filters'
import { Route as ApiFullInvoicedRouteImport } from './routes/api/full-invoiced'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiLostRouteImport } from './routes/api/lost'
import { Route as ApiMediaBuyersRouteImport } from './routes/api/media-buyers'
import { Route as ApiMediaPlanRouteImport } from './routes/api/media-plan'
import { Route as ApiOrganicRouteImport } from './routes/api/organic'
import { Route as ApiOverviewRouteImport } from './routes/api/overview'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiProfitabilityRouteImport } from './routes/api/profitability'
import { Route as ApiRefreshRouteImport } from './routes/api/refresh'
import { Route as ApiSalesRouteImport } from './routes/api/sales'
import { Route as ApiTargetsRouteImport } from './routes/api/targets'
import { Route as ApiTeamsRouteImport } from './routes/api/teams'
import { Route as ApiWebsiteRouteImport } from './routes/api/website'
import { Route as ApiWeekendRouteImport } from './routes/api/weekend'
import { Route as ApiYoyRouteImport } from './routes/api/yoy'
import { Route as ApiAuthSsoRouteImport } from './routes/api/auth.sso'
import { Route as ApiIngestDatasetRouteImport } from './routes/api/ingest.dataset'
import { Route as ApiTelegramPreviewRouteImport } from './routes/api/telegram.preview'
import { Route as ApiTelegramSendCourseAlertsRouteImport } from './routes/api/telegram.send-course-alerts'
import { Route as ApiTelegramSendDailyRouteImport } from './routes/api/telegram.send-daily'
import { Route as ApiTelegramSetupRouteImport } from './routes/api/telegram.setup'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FullInvoicedRoute = FullInvoicedRouteImport.update({
  id: '/full-invoiced',
  path: '/full-invoiced',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaBuyersRoute = MediaBuyersRouteImport.update({
  id: '/media-buyers',
  path: '/media-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaPlanRoute = MediaPlanRouteImport.update({
  id: '/media-plan',
  path: '/media-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganicRoute = OrganicRouteImport.update({
  id: '/organic',
  path: '/organic',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendRoute = WeekendRouteImport.update({
  id: '/weekend',
  path: '/weekend',
  getParentRoute: () => rootRouteImport,
} as any)
const YoyRoute = YoyRouteImport.update({
  id: '/yoy',
  path: '/yoy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountingRoute = ApiAccountingRouteImport.update({
  id: '/api/accounting',
  path: '/api/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountingExportRoute = ApiAccountingExportRouteImport.update({
  id: '/api/accounting-export',
  path: '/api/accounting-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsRoute = ApiAdsRouteImport.update({
  id: '/api/ads',
  path: '/api/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentCourseInvoicesRoute = ApiAgentCourseInvoicesRouteImport.update({
  id: '/api/agent-course-invoices',
  path: '/api/agent-course-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignRiskRoute = ApiCampaignRiskRouteImport.update({
  id: '/api/campaign-risk',
  path: '/api/campaign-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseLeadAlertsRoute = ApiCourseLeadAlertsRouteImport.update({
  id: '/api/course-lead-alerts',
  path: '/api/course-lead-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesRoute = ApiCoursesRouteImport.update({
  id: '/api/courses',
  path: '/api/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeCallDetailRoute = ApiEmployeeCallDetailRouteImport.update({
  id: '/api/employee-call-detail',
  path: '/api/employee-call-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeCallRecordingRoute =
  ApiEmployeeCallRecordingRouteImport.update({
    id: '/api/employee-call-recording',
    path: '/api/employee-call-recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmployeeCallsRoute = ApiEmployeeCallsRouteImport.update({
  id: '/api/employee-calls',
  path: '/api/employee-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeEvidenceRoute = ApiEmployeeEvidenceRouteImport.update({
  id: '/api/employee-evidence',
  path: '/api/employee-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFiltersRoute = ApiFiltersRouteImport.update({
  id: '/api/filters',
  path: '/api/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFullInvoicedRoute = ApiFullInvoicedRouteImport.update({
  id: '/api/full-invoiced',
  path: '/api/full-invoiced',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLostRoute = ApiLostRouteImport.update({
  id: '/api/lost',
  path: '/api/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaBuyersRoute = ApiMediaBuyersRouteImport.update({
  id: '/api/media-buyers',
  path: '/api/media-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaPlanRoute = ApiMediaPlanRouteImport.update({
  id: '/api/media-plan',
  path: '/api/media-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganicRoute = ApiOrganicRouteImport.update({
  id: '/api/organic',
  path: '/api/organic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverviewRoute = ApiOverviewRouteImport.update({
  id: '/api/overview',
  path: '/api/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfitabilityRoute = ApiProfitabilityRouteImport.update({
  id: '/api/profitability',
  path: '/api/profitability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefreshRoute = ApiRefreshRouteImport.update({
  id: '/api/refresh',
  path: '/api/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesRoute = ApiSalesRouteImport.update({
  id: '/api/sales',
  path: '/api/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTargetsRoute = ApiTargetsRouteImport.update({
  id: '/api/targets',
  path: '/api/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsRoute = ApiTeamsRouteImport.update({
  id: '/api/teams',
  path: '/api/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebsiteRoute = ApiWebsiteRouteImport.update({
  id: '/api/website',
  path: '/api/website',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeekendRoute = ApiWeekendRouteImport.update({
  id: '/api/weekend',
  path: '/api/weekend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoyRoute = ApiYoyRouteImport.update({
  id: '/api/yoy',
  path: '/api/yoy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSsoRoute = ApiAuthSsoRouteImport.update({
  id: '/api/auth/sso',
  path: '/api/auth/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestDatasetRoute = ApiIngestDatasetRouteImport.update({
  id: '/api/ingest/dataset',
  path: '/api/ingest/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramPreviewRoute = ApiTelegramPreviewRouteImport.update({
  id: '/api/telegram/preview',
  path: '/api/telegram/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSendCourseAlertsRoute =
  ApiTelegramSendCourseAlertsRouteImport.update({
    id: '/api/telegram/send-course-alerts',
    path: '/api/telegram/send-course-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTelegramSendDailyRoute = ApiTelegramSendDailyRouteImport.update({
  id: '/api/telegram/send-daily',
  path: '/api/telegram/send-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSetupRoute = ApiTelegramSetupRouteImport.update({
  id: '/api/telegram/setup',
  path: '/api/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/ads': typeof AdsRoute
  '/campaigns': typeof CampaignsRoute
  '/courses': typeof CoursesRoute
  '/full-invoiced': typeof FullInvoicedRoute
  '/guide': typeof GuideRoute
  '/leads': typeof LeadsRoute
  '/lost': typeof LostRoute
  '/media-buyers': typeof MediaBuyersRoute
  '/media-plan': typeof MediaPlanRoute
  '/organic': typeof OrganicRoute
  '/products': typeof ProductsRoute
  '/sales': typeof SalesRoute
  '/social-media': typeof SocialMediaRoute
  '/teams': typeof TeamsRoute
  '/website': typeof WebsiteRoute
  '/weekend': typeof WeekendRoute
  '/yoy': typeof YoyRoute
  '/api/accounting': typeof ApiAccountingRoute
  '/api/accounting-export': typeof ApiAccountingExportRoute
  '/api/ads': typeof ApiAdsRoute
  '/api/agent-course-invoices': typeof ApiAgentCourseInvoicesRoute
  '/api/campaign-risk': typeof ApiCampaignRiskRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/course-lead-alerts': typeof ApiCourseLeadAlertsRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/employee-call-detail': typeof ApiEmployeeCallDetailRoute
  '/api/employee-call-recording': typeof ApiEmployeeCallRecordingRoute
  '/api/employee-calls': typeof ApiEmployeeCallsRoute
  '/api/employee-evidence': typeof ApiEmployeeEvidenceRoute
  '/api/filters': typeof ApiFiltersRoute
  '/api/full-invoiced': typeof ApiFullInvoicedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lost': typeof ApiLostRoute
  '/api/media-buyers': typeof ApiMediaBuyersRoute
  '/api/media-plan': typeof ApiMediaPlanRoute
  '/api/organic': typeof ApiOrganicRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/products': typeof ApiProductsRoute
  '/api/profitability': typeof ApiProfitabilityRoute
  '/api/refresh': typeof ApiRefreshRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/targets': typeof ApiTargetsRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/website': typeof ApiWebsiteRoute
  '/api/weekend': typeof ApiWeekendRoute
  '/api/yoy': typeof ApiYoyRoute
  '/api/auth/sso': typeof ApiAuthSsoRoute
  '/api/ingest/dataset': typeof ApiIngestDatasetRoute
  '/api/telegram/preview': typeof ApiTelegramPreviewRoute
  '/api/telegram/send-course-alerts': typeof ApiTelegramSendCourseAlertsRoute
  '/api/telegram/send-daily': typeof ApiTelegramSendDailyRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/ads': typeof AdsRoute
  '/campaigns': typeof CampaignsRoute
  '/courses': typeof CoursesRoute
  '/full-invoiced': typeof FullInvoicedRoute
  '/guide': typeof GuideRoute
  '/leads': typeof LeadsRoute
  '/lost': typeof LostRoute
  '/media-buyers': typeof MediaBuyersRoute
  '/media-plan': typeof MediaPlanRoute
  '/organic': typeof OrganicRoute
  '/products': typeof ProductsRoute
  '/sales': typeof SalesRoute
  '/social-media': typeof SocialMediaRoute
  '/teams': typeof TeamsRoute
  '/website': typeof WebsiteRoute
  '/weekend': typeof WeekendRoute
  '/yoy': typeof YoyRoute
  '/api/accounting': typeof ApiAccountingRoute
  '/api/accounting-export': typeof ApiAccountingExportRoute
  '/api/ads': typeof ApiAdsRoute
  '/api/agent-course-invoices': typeof ApiAgentCourseInvoicesRoute
  '/api/campaign-risk': typeof ApiCampaignRiskRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/course-lead-alerts': typeof ApiCourseLeadAlertsRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/employee-call-detail': typeof ApiEmployeeCallDetailRoute
  '/api/employee-call-recording': typeof ApiEmployeeCallRecordingRoute
  '/api/employee-calls': typeof ApiEmployeeCallsRoute
  '/api/employee-evidence': typeof ApiEmployeeEvidenceRoute
  '/api/filters': typeof ApiFiltersRoute
  '/api/full-invoiced': typeof ApiFullInvoicedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lost': typeof ApiLostRoute
  '/api/media-buyers': typeof ApiMediaBuyersRoute
  '/api/media-plan': typeof ApiMediaPlanRoute
  '/api/organic': typeof ApiOrganicRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/products': typeof ApiProductsRoute
  '/api/profitability': typeof ApiProfitabilityRoute
  '/api/refresh': typeof ApiRefreshRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/targets': typeof ApiTargetsRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/website': typeof ApiWebsiteRoute
  '/api/weekend': typeof ApiWeekendRoute
  '/api/yoy': typeof ApiYoyRoute
  '/api/auth/sso': typeof ApiAuthSsoRoute
  '/api/ingest/dataset': typeof ApiIngestDatasetRoute
  '/api/telegram/preview': typeof ApiTelegramPreviewRoute
  '/api/telegram/send-course-alerts': typeof ApiTelegramSendCourseAlertsRoute
  '/api/telegram/send-daily': typeof ApiTelegramSendDailyRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/ads': typeof AdsRoute
  '/campaigns': typeof CampaignsRoute
  '/courses': typeof CoursesRoute
  '/full-invoiced': typeof FullInvoicedRoute
  '/guide': typeof GuideRoute
  '/leads': typeof LeadsRoute
  '/lost': typeof LostRoute
  '/media-buyers': typeof MediaBuyersRoute
  '/media-plan': typeof MediaPlanRoute
  '/organic': typeof OrganicRoute
  '/products': typeof ProductsRoute
  '/sales': typeof SalesRoute
  '/social-media': typeof SocialMediaRoute
  '/teams': typeof TeamsRoute
  '/website': typeof WebsiteRoute
  '/weekend': typeof WeekendRoute
  '/yoy': typeof YoyRoute
  '/api/accounting': typeof ApiAccountingRoute
  '/api/accounting-export': typeof ApiAccountingExportRoute
  '/api/ads': typeof ApiAdsRoute
  '/api/agent-course-invoices': typeof ApiAgentCourseInvoicesRoute
  '/api/campaign-risk': typeof ApiCampaignRiskRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/course-lead-alerts': typeof ApiCourseLeadAlertsRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/employee-call-detail': typeof ApiEmployeeCallDetailRoute
  '/api/employee-call-recording': typeof ApiEmployeeCallRecordingRoute
  '/api/employee-calls': typeof ApiEmployeeCallsRoute
  '/api/employee-evidence': typeof ApiEmployeeEvidenceRoute
  '/api/filters': typeof ApiFiltersRoute
  '/api/full-invoiced': typeof ApiFullInvoicedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/lost': typeof ApiLostRoute
  '/api/media-buyers': typeof ApiMediaBuyersRoute
  '/api/media-plan': typeof ApiMediaPlanRoute
  '/api/organic': typeof ApiOrganicRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/products': typeof ApiProductsRoute
  '/api/profitability': typeof ApiProfitabilityRoute
  '/api/refresh': typeof ApiRefreshRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/targets': typeof ApiTargetsRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/website': typeof ApiWebsiteRoute
  '/api/weekend': typeof ApiWeekendRoute
  '/api/yoy': typeof ApiYoyRoute
  '/api/auth/sso': typeof ApiAuthSsoRoute
  '/api/ingest/dataset': typeof ApiIngestDatasetRoute
  '/api/telegram/preview': typeof ApiTelegramPreviewRoute
  '/api/telegram/send-course-alerts': typeof ApiTelegramSendCourseAlertsRoute
  '/api/telegram/send-daily': typeof ApiTelegramSendDailyRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/ads'
    | '/campaigns'
    | '/courses'
    | '/full-invoiced'
    | '/guide'
    | '/leads'
    | '/lost'
    | '/media-buyers'
    | '/media-plan'
    | '/organic'
    | '/products'
    | '/sales'
    | '/social-media'
    | '/teams'
    | '/website'
    | '/weekend'
    | '/yoy'
    | '/api/accounting'
    | '/api/accounting-export'
    | '/api/ads'
    | '/api/agent-course-invoices'
    | '/api/campaign-risk'
    | '/api/campaigns'
    | '/api/chat'
    | '/api/course-lead-alerts'
    | '/api/courses'
    | '/api/employee-call-detail'
    | '/api/employee-call-recording'
    | '/api/employee-calls'
    | '/api/employee-evidence'
    | '/api/filters'
    | '/api/full-invoiced'
    | '/api/health'
    | '/api/leads'
    | '/api/lost'
    | '/api/media-buyers'
    | '/api/media-plan'
    | '/api/organic'
    | '/api/overview'
    | '/api/products'
    | '/api/profitability'
    | '/api/refresh'
    | '/api/sales'
    | '/api/targets'
    | '/api/teams'
    | '/api/website'
    | '/api/weekend'
    | '/api/yoy'
    | '/api/auth/sso'
    | '/api/ingest/dataset'
    | '/api/telegram/preview'
    | '/api/telegram/send-course-alerts'
    | '/api/telegram/send-daily'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/ads'
    | '/campaigns'
    | '/courses'
    | '/full-invoiced'
    | '/guide'
    | '/leads'
    | '/lost'
    | '/media-buyers'
    | '/media-plan'
    | '/organic'
    | '/products'
    | '/sales'
    | '/social-media'
    | '/teams'
    | '/website'
    | '/weekend'
    | '/yoy'
    | '/api/accounting'
    | '/api/accounting-export'
    | '/api/ads'
    | '/api/agent-course-invoices'
    | '/api/campaign-risk'
    | '/api/campaigns'
    | '/api/chat'
    | '/api/course-lead-alerts'
    | '/api/courses'
    | '/api/employee-call-detail'
    | '/api/employee-call-recording'
    | '/api/employee-calls'
    | '/api/employee-evidence'
    | '/api/filters'
    | '/api/full-invoiced'
    | '/api/health'
    | '/api/leads'
    | '/api/lost'
    | '/api/media-buyers'
    | '/api/media-plan'
    | '/api/organic'
    | '/api/overview'
    | '/api/products'
    | '/api/profitability'
    | '/api/refresh'
    | '/api/sales'
    | '/api/targets'
    | '/api/teams'
    | '/api/website'
    | '/api/weekend'
    | '/api/yoy'
    | '/api/auth/sso'
    | '/api/ingest/dataset'
    | '/api/telegram/preview'
    | '/api/telegram/send-course-alerts'
    | '/api/telegram/send-daily'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/ads'
    | '/campaigns'
    | '/courses'
    | '/full-invoiced'
    | '/guide'
    | '/leads'
    | '/lost'
    | '/media-buyers'
    | '/media-plan'
    | '/organic'
    | '/products'
    | '/sales'
    | '/social-media'
    | '/teams'
    | '/website'
    | '/weekend'
    | '/yoy'
    | '/api/accounting'
    | '/api/accounting-export'
    | '/api/ads'
    | '/api/agent-course-invoices'
    | '/api/campaign-risk'
    | '/api/campaigns'
    | '/api/chat'
    | '/api/course-lead-alerts'
    | '/api/courses'
    | '/api/employee-call-detail'
    | '/api/employee-call-recording'
    | '/api/employee-calls'
    | '/api/employee-evidence'
    | '/api/filters'
    | '/api/full-invoiced'
    | '/api/health'
    | '/api/leads'
    | '/api/lost'
    | '/api/media-buyers'
    | '/api/media-plan'
    | '/api/organic'
    | '/api/overview'
    | '/api/products'
    | '/api/profitability'
    | '/api/refresh'
    | '/api/sales'
    | '/api/targets'
    | '/api/teams'
    | '/api/website'
    | '/api/weekend'
    | '/api/yoy'
    | '/api/auth/sso'
    | '/api/ingest/dataset'
    | '/api/telegram/preview'
    | '/api/telegram/send-course-alerts'
    | '/api/telegram/send-daily'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AdsRoute: typeof AdsRoute
  CampaignsRoute: typeof CampaignsRoute
  CoursesRoute: typeof CoursesRoute
  FullInvoicedRoute: typeof FullInvoicedRoute
  GuideRoute: typeof GuideRoute
  LeadsRoute: typeof LeadsRoute
  LostRoute: typeof LostRoute
  MediaBuyersRoute: typeof MediaBuyersRoute
  MediaPlanRoute: typeof MediaPlanRoute
  OrganicRoute: typeof OrganicRoute
  ProductsRoute: typeof ProductsRoute
  SalesRoute: typeof SalesRoute
  SocialMediaRoute: typeof SocialMediaRoute
  TeamsRoute: typeof TeamsRoute
  WebsiteRoute: typeof WebsiteRoute
  WeekendRoute: typeof WeekendRoute
  YoyRoute: typeof YoyRoute
  ApiAccountingRoute: typeof ApiAccountingRoute
  ApiAccountingExportRoute: typeof ApiAccountingExportRoute
  ApiAdsRoute: typeof ApiAdsRoute
  ApiAgentCourseInvoicesRoute: typeof ApiAgentCourseInvoicesRoute
  ApiCampaignRiskRoute: typeof ApiCampaignRiskRoute
  ApiCampaignsRoute: typeof ApiCampaignsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCourseLeadAlertsRoute: typeof ApiCourseLeadAlertsRoute
  ApiCoursesRoute: typeof ApiCoursesRoute
  ApiEmployeeCallDetailRoute: typeof ApiEmployeeCallDetailRoute
  ApiEmployeeCallRecordingRoute: typeof ApiEmployeeCallRecordingRoute
  ApiEmployeeCallsRoute: typeof ApiEmployeeCallsRoute
  ApiEmployeeEvidenceRoute: typeof ApiEmployeeEvidenceRoute
  ApiFiltersRoute: typeof ApiFiltersRoute
  ApiFullInvoicedRoute: typeof ApiFullInvoicedRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiLostRoute: typeof ApiLostRoute
  ApiMediaBuyersRoute: typeof ApiMediaBuyersRoute
  ApiMediaPlanRoute: typeof ApiMediaPlanRoute
  ApiOrganicRoute: typeof ApiOrganicRoute
  ApiOverviewRoute: typeof ApiOverviewRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiProfitabilityRoute: typeof ApiProfitabilityRoute
  ApiRefreshRoute: typeof ApiRefreshRoute
  ApiSalesRoute: typeof ApiSalesRoute
  ApiTargetsRoute: typeof ApiTargetsRoute
  ApiTeamsRoute: typeof ApiTeamsRoute
  ApiWebsiteRoute: typeof ApiWebsiteRoute
  ApiWeekendRoute: typeof ApiWeekendRoute
  ApiYoyRoute: typeof ApiYoyRoute
  ApiAuthSsoRoute: typeof ApiAuthSsoRoute
  ApiIngestDatasetRoute: typeof ApiIngestDatasetRoute
  ApiTelegramPreviewRoute: typeof ApiTelegramPreviewRoute
  ApiTelegramSendCourseAlertsRoute: typeof ApiTelegramSendCourseAlertsRoute
  ApiTelegramSendDailyRoute: typeof ApiTelegramSendDailyRoute
  ApiTelegramSetupRoute: typeof ApiTelegramSetupRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-invoiced': {
      id: '/full-invoiced'
      path: '/full-invoiced'
      fullPath: '/full-invoiced'
      preLoaderRoute: typeof FullInvoicedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-buyers': {
      id: '/media-buyers'
      path: '/media-buyers'
      fullPath: '/media-buyers'
      preLoaderRoute: typeof MediaBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-plan': {
      id: '/media-plan'
      path: '/media-plan'
      fullPath: '/media-plan'
      preLoaderRoute: typeof MediaPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organic': {
      id: '/organic'
      path: '/organic'
      fullPath: '/organic'
      preLoaderRoute: typeof OrganicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend': {
      id: '/weekend'
      path: '/weekend'
      fullPath: '/weekend'
      preLoaderRoute: typeof WeekendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoy': {
      id: '/yoy'
      path: '/yoy'
      fullPath: '/yoy'
      preLoaderRoute: typeof YoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounting': {
      id: '/api/accounting'
      path: '/api/accounting'
      fullPath: '/api/accounting'
      preLoaderRoute: typeof ApiAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounting-export': {
      id: '/api/accounting-export'
      path: '/api/accounting-export'
      fullPath: '/api/accounting-export'
      preLoaderRoute: typeof ApiAccountingExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads': {
      id: '/api/ads'
      path: '/api/ads'
      fullPath: '/api/ads'
      preLoaderRoute: typeof ApiAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-course-invoices': {
      id: '/api/agent-course-invoices'
      path: '/api/agent-course-invoices'
      fullPath: '/api/agent-course-invoices'
      preLoaderRoute: typeof ApiAgentCourseInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaign-risk': {
      id: '/api/campaign-risk'
      path: '/api/campaign-risk'
      fullPath: '/api/campaign-risk'
      preLoaderRoute: typeof ApiCampaignRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course-lead-alerts': {
      id: '/api/course-lead-alerts'
      path: '/api/course-lead-alerts'
      fullPath: '/api/course-lead-alerts'
      preLoaderRoute: typeof ApiCourseLeadAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses': {
      id: '/api/courses'
      path: '/api/courses'
      fullPath: '/api/courses'
      preLoaderRoute: typeof ApiCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee-call-detail': {
      id: '/api/employee-call-detail'
      path: '/api/employee-call-detail'
      fullPath: '/api/employee-call-detail'
      preLoaderRoute: typeof ApiEmployeeCallDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee-call-recording': {
      id: '/api/employee-call-recording'
      path: '/api/employee-call-recording'
      fullPath: '/api/employee-call-recording'
      preLoaderRoute: typeof ApiEmployeeCallRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee-calls': {
      id: '/api/employee-calls'
      path: '/api/employee-calls'
      fullPath: '/api/employee-calls'
      preLoaderRoute: typeof ApiEmployeeCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee-evidence': {
      id: '/api/employee-evidence'
      path: '/api/employee-evidence'
      fullPath: '/api/employee-evidence'
      preLoaderRoute: typeof ApiEmployeeEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/filters': {
      id: '/api/filters'
      path: '/api/filters'
      fullPath: '/api/filters'
      preLoaderRoute: typeof ApiFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/full-invoiced': {
      id: '/api/full-invoiced'
      path: '/api/full-invoiced'
      fullPath: '/api/full-invoiced'
      preLoaderRoute: typeof ApiFullInvoicedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lost': {
      id: '/api/lost'
      path: '/api/lost'
      fullPath: '/api/lost'
      preLoaderRoute: typeof ApiLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-buyers': {
      id: '/api/media-buyers'
      path: '/api/media-buyers'
      fullPath: '/api/media-buyers'
      preLoaderRoute: typeof ApiMediaBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-plan': {
      id: '/api/media-plan'
      path: '/api/media-plan'
      fullPath: '/api/media-plan'
      preLoaderRoute: typeof ApiMediaPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organic': {
      id: '/api/organic'
      path: '/api/organic'
      fullPath: '/api/organic'
      preLoaderRoute: typeof ApiOrganicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overview': {
      id: '/api/overview'
      path: '/api/overview'
      fullPath: '/api/overview'
      preLoaderRoute: typeof ApiOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profitability': {
      id: '/api/profitability'
      path: '/api/profitability'
      fullPath: '/api/profitability'
      preLoaderRoute: typeof ApiProfitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refresh': {
      id: '/api/refresh'
      path: '/api/refresh'
      fullPath: '/api/refresh'
      preLoaderRoute: typeof ApiRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales': {
      id: '/api/sales'
      path: '/api/sales'
      fullPath: '/api/sales'
      preLoaderRoute: typeof ApiSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/targets': {
      id: '/api/targets'
      path: '/api/targets'
      fullPath: '/api/targets'
      preLoaderRoute: typeof ApiTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams': {
      id: '/api/teams'
      path: '/api/teams'
      fullPath: '/api/teams'
      preLoaderRoute: typeof ApiTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/website': {
      id: '/api/website'
      path: '/api/website'
      fullPath: '/api/website'
      preLoaderRoute: typeof ApiWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekend': {
      id: '/api/weekend'
      path: '/api/weekend'
      fullPath: '/api/weekend'
      preLoaderRoute: typeof ApiWeekendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yoy': {
      id: '/api/yoy'
      path: '/api/yoy'
      fullPath: '/api/yoy'
      preLoaderRoute: typeof ApiYoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sso': {
      id: '/api/auth/sso'
      path: '/api/auth/sso'
      fullPath: '/api/auth/sso'
      preLoaderRoute: typeof ApiAuthSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/dataset': {
      id: '/api/ingest/dataset'
      path: '/api/ingest/dataset'
      fullPath: '/api/ingest/dataset'
      preLoaderRoute: typeof ApiIngestDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/preview': {
      id: '/api/telegram/preview'
      path: '/api/telegram/preview'
      fullPath: '/api/telegram/preview'
      preLoaderRoute: typeof ApiTelegramPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/send-course-alerts': {
      id: '/api/telegram/send-course-alerts'
      path: '/api/telegram/send-course-alerts'
      fullPath: '/api/telegram/send-course-alerts'
      preLoaderRoute: typeof ApiTelegramSendCourseAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/send-daily': {
      id: '/api/telegram/send-daily'
      path: '/api/telegram/send-daily'
      fullPath: '/api/telegram/send-daily'
      preLoaderRoute: typeof ApiTelegramSendDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/setup': {
      id: '/api/telegram/setup'
      path: '/api/telegram/setup'
      fullPath: '/api/telegram/setup'
      preLoaderRoute: typeof ApiTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AdsRoute: AdsRoute,
  CampaignsRoute: CampaignsRoute,
  CoursesRoute: CoursesRoute,
  FullInvoicedRoute: FullInvoicedRoute,
  GuideRoute: GuideRoute,
  LeadsRoute: LeadsRoute,
  LostRoute: LostRoute,
  MediaBuyersRoute: MediaBuyersRoute,
  MediaPlanRoute: MediaPlanRoute,
  OrganicRoute: OrganicRoute,
  ProductsRoute: ProductsRoute,
  SalesRoute: SalesRoute,
  SocialMediaRoute: SocialMediaRoute,
  TeamsRoute: TeamsRoute,
  WebsiteRoute: WebsiteRoute,
  WeekendRoute: WeekendRoute,
  YoyRoute: YoyRoute,
  ApiAccountingRoute: ApiAccountingRoute,
  ApiAccountingExportRoute: ApiAccountingExportRoute,
  ApiAdsRoute: ApiAdsRoute,
  ApiAgentCourseInvoicesRoute: ApiAgentCourseInvoicesRoute,
  ApiCampaignRiskRoute: ApiCampaignRiskRoute,
  ApiCampaignsRoute: ApiCampaignsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCourseLeadAlertsRoute: ApiCourseLeadAlertsRoute,
  ApiCoursesRoute: ApiCoursesRoute,
  ApiEmployeeCallDetailRoute: ApiEmployeeCallDetailRoute,
  ApiEmployeeCallRecordingRoute: ApiEmployeeCallRecordingRoute,
  ApiEmployeeCallsRoute: ApiEmployeeCallsRoute,
  ApiEmployeeEvidenceRoute: ApiEmployeeEvidenceRoute,
  ApiFiltersRoute: ApiFiltersRoute,
  ApiFullInvoicedRoute: ApiFullInvoicedRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiLostRoute: ApiLostRoute,
  ApiMediaBuyersRoute: ApiMediaBuyersRoute,
  ApiMediaPlanRoute: ApiMediaPlanRoute,
  ApiOrganicRoute: ApiOrganicRoute,
  ApiOverviewRoute: ApiOverviewRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiProfitabilityRoute: ApiProfitabilityRoute,
  ApiRefreshRoute: ApiRefreshRoute,
  ApiSalesRoute: ApiSalesRoute,
  ApiTargetsRoute: ApiTargetsRoute,
  ApiTeamsRoute: ApiTeamsRoute,
  ApiWebsiteRoute: ApiWebsiteRoute,
  ApiWeekendRoute: ApiWeekendRoute,
  ApiYoyRoute: ApiYoyRoute,
  ApiAuthSsoRoute: ApiAuthSsoRoute,
  ApiIngestDatasetRoute: ApiIngestDatasetRoute,
  ApiTelegramPreviewRoute: ApiTelegramPreviewRoute,
  ApiTelegramSendCourseAlertsRoute: ApiTelegramSendCourseAlertsRoute,
  ApiTelegramSendDailyRoute: ApiTelegramSendDailyRoute,
  ApiTelegramSetupRoute: ApiTelegramSetupRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
